#:schema node_modules/wrangler/config-schema.json
# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/
name = "replicate-model-classifier"
main = "src/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = [ "nodejs_compat" ]

kv_namespaces = [
  { binding = "CLASSIFICATIONS_CACHE", id = "e8c439371ebb495ebd9549366e8a130f" }
]

