#:schema node_modules/wrangler/config-schema.json
# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/
name = "replicate-model-classifier"
main = "src/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = [ "nodejs_compat" ]

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "replicate-classifier-cache"
database_id = "b9096b5c-0dfd-4af7-886a-c0cacb1ead65"



